// Generated by scripts/build-address-pool.js. Do not edit by hand.
// Source: data/address-pool/*.json
// Generated at: 2026-10-02T06:15:51.625Z
const LOCAL_VERIFIED_ADDRESS_POOL_DATA = {
  "Australia": [
    {
      "address": "1 Macquarie St",
      "city": "Sydney",
      "state": "New South Wales",
      "zipCode": "2000"
    },
    {
      "address": "200 George St",
      "city": "Sydney",
      "state": "New South Wales",
      "zipCode": "2000"
    },
    {
      "address": "101 Collins St",
      "city": "Melbourne",
      "state": "Victoria",
      "zipCode": "3000"
    },
    {
      "address": "480 Queen St",
      "city": "Brisbane",
      "state": "Queensland",
      "zipCode": "4000"
    },
    {
      "address": "240 St Georges Terrace",
      "city": "Perth",
      "state": "Western Australia",
      "zipCode": "6000"
    },
    {
      "address": "1 King William St",
      "city": "Adelaide",
      "state": "South Australia",
      "zipCode": "5000"
    },
    {
      "address": "15 London Cct",
      "city": "Canberra",
      "state": "Australian Capital Territory",
      "zipCode": "2601"
    },
    {
      "address": "89 Macquarie St",
      "city": "Hobart",
      "state": "Tasmania",
      "zipCode": "7000"
    },
    {
      "address": "12 Smith St",
      "city": "Darwin",
      "state": "Northern Territory",
      "zipCode": "0800"
    },
    {
      "address": "50 Cavill Ave",
      "city": "Gold Coast",
      "state": "Queensland",
      "zipCode": "4217"
    },
    {
      "address": "1 Martin Place",
      "city": "Sydney",
      "state": "New South Wales",
      "zipCode": "2000"
    },
    {
      "address": "120 Collins St",
      "city": "Melbourne",
      "state": "Victoria",
      "zipCode": "3000"
    },
    {
      "address": "100 Eagle St",
      "city": "Brisbane",
      "state": "Queensland",
      "zipCode": "4000"
    },
    {
      "address": "77 St Georges Terrace",
      "city": "Perth",
      "state": "Western Australia",
      "zipCode": "6000"
    },
    {
      "address": "91 King William St",
      "city": "Adelaide",
      "state": "South Australia",
      "zipCode": "5000"
    },
    {
      "address": "1 Constitution Ave",
      "city": "Canberra",
      "state": "Australian Capital Territory",
      "zipCode": "2600"
    },
    {
      "address": "25 Murray St",
      "city": "Hobart",
      "state": "Tasmania",
      "zipCode": "7000"
    },
    {
      "address": "48 Mitchell St",
      "city": "Darwin",
      "state": "Northern Territory",
      "zipCode": "0800"
    },
    {
      "address": "2 Surf Parade",
      "city": "Gold Coast",
      "state": "Queensland",
      "zipCode": "4217"
    },
    {
      "address": "1 Bligh St",
      "city": "Sydney",
      "state": "New South Wales",
      "zipCode": "2000"
    },
    {
      "address": "530 Collins St",
      "city": "Melbourne",
      "state": "Victoria",
      "zipCode": "3000"
    },
    {
      "address": "111 Eagle St",
      "city": "Brisbane",
      "state": "Queensland",
      "zipCode": "4000"
    },
    {
      "address": "108 St Georges Terrace",
      "city": "Perth",
      "state": "Western Australia",
      "zipCode": "6000"
    },
    {
      "address": "70 Hindmarsh Square",
      "city": "Adelaide",
      "state": "South Australia",
      "zipCode": "5000"
    },
    {
      "address": "40 Marcus Clarke St",
      "city": "Canberra",
      "state": "Australian Capital Territory",
      "zipCode": "2601"
    },
    {
      "address": "1 Elizabeth St",
      "city": "Hobart",
      "state": "Tasmania",
      "zipCode": "7000"
    },
    {
      "address": "19 The Mall",
      "city": "Darwin",
      "state": "Northern Territory",
      "zipCode": "0800"
    },
    {
      "address": "9 Park Lane",
      "city": "Gold Coast",
      "state": "Queensland",
      "zipCode": "4217"
    },
    {
      "address": "88 Phillip St",
      "city": "Sydney",
      "state": "New South Wales",
      "zipCode": "2000"
    },
    {
      "address": "360 Collins St",
      "city": "Melbourne",
      "state": "Victoria",
      "zipCode": "3000"
    }
  ],
  "Brazil": [
    {
      "address": "Avenida Paulista 1578",
      "city": "Sao Paulo",
      "state": "Sao Paulo",
      "zipCode": "01310-200"
    },
    {
      "address": "Rua Augusta 1200",
      "city": "Sao Paulo",
      "state": "Sao Paulo",
      "zipCode": "01304-001"
    },
    {
      "address": "Avenida Atlantica 1702",
      "city": "Rio de Janeiro",
      "state": "Rio de Janeiro",
      "zipCode": "22021-001"
    },
    {
      "address": "Rua do Catete 120",
      "city": "Rio de Janeiro",
      "state": "Rio de Janeiro",
      "zipCode": "22220-000"
    },
    {
      "address": "SCS Quadra 2 Bloco C",
      "city": "Brasilia",
      "state": "Federal District",
      "zipCode": "70300-902"
    },
    {
      "address": "Avenida Sete de Setembro 2500",
      "city": "Salvador",
      "state": "Bahia",
      "zipCode": "40080-001"
    },
    {
      "address": "Avenida Beira Mar 2200",
      "city": "Fortaleza",
      "state": "Ceara",
      "zipCode": "60165-121"
    },
    {
      "address": "Avenida Afonso Pena 3000",
      "city": "Belo Horizonte",
      "state": "Minas Gerais",
      "zipCode": "30130-009"
    },
    {
      "address": "Rua XV de Novembro 450",
      "city": "Curitiba",
      "state": "Parana",
      "zipCode": "80020-310"
    },
    {
      "address": "Avenida Boa Viagem 800",
      "city": "Recife",
      "state": "Pernambuco",
      "zipCode": "51011-000"
    },
    {
      "address": "Avenida Paulista 330",
      "city": "Sao Paulo",
      "state": "Sao Paulo",
      "zipCode": "01310-200"
    },
    {
      "address": "Avenida Paulista 1388",
      "city": "Sao Paulo",
      "state": "Sao Paulo",
      "zipCode": "01310-200"
    },
    {
      "address": "Rua Augusta 290",
      "city": "Sao Paulo",
      "state": "Sao Paulo",
      "zipCode": "01304-001"
    },
    {
      "address": "Rua Augusta 1109",
      "city": "Sao Paulo",
      "state": "Sao Paulo",
      "zipCode": "01304-001"
    },
    {
      "address": "Avenida Atlantica 759",
      "city": "Rio de Janeiro",
      "state": "Rio de Janeiro",
      "zipCode": "22021-001"
    },
    {
      "address": "Avenida Atlantica 832",
      "city": "Rio de Janeiro",
      "state": "Rio de Janeiro",
      "zipCode": "22021-001"
    },
    {
      "address": "Rua do Catete 1435",
      "city": "Rio de Janeiro",
      "state": "Rio de Janeiro",
      "zipCode": "22220-000"
    },
    {
      "address": "Rua do Catete 724",
      "city": "Rio de Janeiro",
      "state": "Rio de Janeiro",
      "zipCode": "22220-000"
    },
    {
      "address": "Avenida Sete de Setembro 192",
      "city": "Salvador",
      "state": "Bahia",
      "zipCode": "40080-001"
    },
    {
      "address": "Avenida Sete de Setembro 1333",
      "city": "Salvador",
      "state": "Bahia",
      "zipCode": "40080-001"
    },
    {
      "address": "Avenida Beira Mar 1021",
      "city": "Fortaleza",
      "state": "Ceara",
      "zipCode": "60165-121"
    },
    {
      "address": "Avenida Beira Mar 649",
      "city": "Fortaleza",
      "state": "Ceara",
      "zipCode": "60165-121"
    },
    {
      "address": "Avenida Afonso Pena 558",
      "city": "Belo Horizonte",
      "state": "Minas Gerais",
      "zipCode": "30130-009"
    },
    {
      "address": "Avenida Afonso Pena 977",
      "city": "Belo Horizonte",
      "state": "Minas Gerais",
      "zipCode": "30130-009"
    },
    {
      "address": "Rua XV de Novembro 1247",
      "city": "Curitiba",
      "state": "Parana",
      "zipCode": "80020-310"
    },
    {
      "address": "Rua XV de Novembro 1253",
      "city": "Curitiba",
      "state": "Parana",
      "zipCode": "80020-310"
    },
    {
      "address": "Avenida Boa Viagem 547",
      "city": "Recife",
      "state": "Pernambuco",
      "zipCode": "51011-000"
    },
    {
      "address": "Avenida Boa Viagem 28",
      "city": "Recife",
      "state": "Pernambuco",
      "zipCode": "51011-000"
    },
    {
      "address": "Avenida Paulista 900",
      "city": "Sao Paulo",
      "state": "Sao Paulo",
      "zipCode": "01310-200"
    },
    {
      "address": "Rua Augusta 350",
      "city": "Sao Paulo",
      "state": "Sao Paulo",
      "zipCode": "01304-001"
    }
  ],
  "Canada": [
    {
      "address": "111 Wellington St",
      "city": "Ottawa",
      "state": "Ontario",
      "zipCode": "K1A 0A9"
    },
    {
      "address": "250 Yonge St",
      "city": "Toronto",
      "state": "Ontario",
      "zipCode": "M5B 2L7"
    },
    {
      "address": "100 Queen St W",
      "city": "Toronto",
      "state": "Ontario",
      "zipCode": "M5H 2N2"
    },
    {
      "address": "845 Hornby St",
      "city": "Vancouver",
      "state": "British Columbia",
      "zipCode": "V6Z 1V1"
    },
    {
      "address": "655 Burrard St",
      "city": "Vancouver",
      "state": "British Columbia",
      "zipCode": "V6C 2R7"
    },
    {
      "address": "1380 Sherbrooke St W",
      "city": "Montreal",
      "state": "Quebec",
      "zipCode": "H3G 1J5"
    },
    {
      "address": "10 Rue Sainte-Catherine O",
      "city": "Montreal",
      "state": "Quebec",
      "zipCode": "H2X 1Z6"
    },
    {
      "address": "9700 Jasper Ave",
      "city": "Edmonton",
      "state": "Alberta",
      "zipCode": "T5J 4C3"
    },
    {
      "address": "200 Portage Ave",
      "city": "Winnipeg",
      "state": "Manitoba",
      "zipCode": "R3C 4X2"
    },
    {
      "address": "700 W Georgia St",
      "city": "Vancouver",
      "state": "British Columbia",
      "zipCode": "V7Y 1K8"
    },
    {
      "address": "150 King St W",
      "city": "Toronto",
      "state": "Ontario",
      "zipCode": "M5H 1J9"
    },
    {
      "address": "1001 Boulevard de Maisonneuve O",
      "city": "Montreal",
      "state": "Quebec",
      "zipCode": "H3A 3C8"
    },
    {
      "address": "421 7 Ave SW",
      "city": "Calgary",
      "state": "Alberta",
      "zipCode": "T2P 4K9"
    },
    {
      "address": "1800 McGill College Ave",
      "city": "Montreal",
      "state": "Quebec",
      "zipCode": "H3A 3J6"
    },
    {
      "address": "100 Queen St",
      "city": "Ottawa",
      "state": "Ontario",
      "zipCode": "K1P 1A5"
    },
    {
      "address": "200 Granville St",
      "city": "Vancouver",
      "state": "British Columbia",
      "zipCode": "V6C 1S4"
    },
    {
      "address": "10180 101 St NW",
      "city": "Edmonton",
      "state": "Alberta",
      "zipCode": "T5J 3S4"
    },
    {
      "address": "201 Portage Ave",
      "city": "Winnipeg",
      "state": "Manitoba",
      "zipCode": "R3B 3K6"
    },
    {
      "address": "1959 Upper Water St",
      "city": "Halifax",
      "state": "Nova Scotia",
      "zipCode": "B3J 3N2"
    },
    {
      "address": "1919 Saskatchewan Dr",
      "city": "Regina",
      "state": "Saskatchewan",
      "zipCode": "S4P 4H2"
    },
    {
      "address": "410 22 St E",
      "city": "Saskatoon",
      "state": "Saskatchewan",
      "zipCode": "S7K 5T6"
    },
    {
      "address": "95 Foundry St",
      "city": "Moncton",
      "state": "New Brunswick",
      "zipCode": "E1C 5H7"
    },
    {
      "address": "100 Water St",
      "city": "St. Johns",
      "state": "Newfoundland and Labrador",
      "zipCode": "A1C 1A1"
    },
    {
      "address": "45 OConnor St",
      "city": "Ottawa",
      "state": "Ontario",
      "zipCode": "K1P 1A4"
    },
    {
      "address": "130 King St W",
      "city": "Toronto",
      "state": "Ontario",
      "zipCode": "M5X 1A9"
    },
    {
      "address": "777 Dunsmuir St",
      "city": "Vancouver",
      "state": "British Columbia",
      "zipCode": "V7Y 1K4"
    },
    {
      "address": "1250 Rene-Levesque Blvd W",
      "city": "Montreal",
      "state": "Quebec",
      "zipCode": "H3B 4W8"
    },
    {
      "address": "350 7 Ave SW",
      "city": "Calgary",
      "state": "Alberta",
      "zipCode": "T2P 3N9"
    },
    {
      "address": "1 Lombard Pl",
      "city": "Winnipeg",
      "state": "Manitoba",
      "zipCode": "R3B 0X3"
    },
    {
      "address": "1801 Hollis St",
      "city": "Halifax",
      "state": "Nova Scotia",
      "zipCode": "B3J 3N4"
    }
  ],
  "China": [
    {
      "address": "1 Chang an Avenue",
      "city": "Beijing",
      "state": "Beijing",
      "zipCode": "100006"
    },
    {
      "address": "99 Wangfujing Street",
      "city": "Beijing",
      "state": "Beijing",
      "zipCode": "100005"
    },
    {
      "address": "100 Nanjing Road East",
      "city": "Shanghai",
      "state": "Shanghai",
      "zipCode": "200001"
    },
    {
      "address": "88 Huaihai Road",
      "city": "Shanghai",
      "state": "Shanghai",
      "zipCode": "200020"
    },
    {
      "address": "200 Tianhe Road",
      "city": "Guangzhou",
      "state": "Guangdong",
      "zipCode": "510620"
    },
    {
      "address": "1 Shennan Avenue",
      "city": "Shenzhen",
      "state": "Guangdong",
      "zipCode": "518000"
    },
    {
      "address": "168 West Lake Avenue",
      "city": "Hangzhou",
      "state": "Zhejiang",
      "zipCode": "310007"
    },
    {
      "address": "300 Jiefang Road",
      "city": "Chengdu",
      "state": "Sichuan",
      "zipCode": "610015"
    },
    {
      "address": "66 Zhongshan Road",
      "city": "Nanjing",
      "state": "Jiangsu",
      "zipCode": "210005"
    },
    {
      "address": "88 Renmin Road",
      "city": "Wuhan",
      "state": "Hubei",
      "zipCode": "430014"
    },
    {
      "address": "1 Jianguomen Outer Street",
      "city": "Beijing",
      "state": "Beijing",
      "zipCode": "100004"
    },
    {
      "address": "100 Century Avenue",
      "city": "Shanghai",
      "state": "Shanghai",
      "zipCode": "200120"
    },
    {
      "address": "68 Zhongshan 5th Road",
      "city": "Guangzhou",
      "state": "Guangdong",
      "zipCode": "510055"
    },
    {
      "address": "5001 Binhai Avenue",
      "city": "Shenzhen",
      "state": "Guangdong",
      "zipCode": "518054"
    },
    {
      "address": "1 Wulin Square",
      "city": "Hangzhou",
      "state": "Zhejiang",
      "zipCode": "310006"
    },
    {
      "address": "1 Tianfu Avenue",
      "city": "Chengdu",
      "state": "Sichuan",
      "zipCode": "610041"
    },
    {
      "address": "1 Xinjiekou",
      "city": "Nanjing",
      "state": "Jiangsu",
      "zipCode": "210005"
    },
    {
      "address": "1 Jiefang Avenue",
      "city": "Wuhan",
      "state": "Hubei",
      "zipCode": "430022"
    },
    {
      "address": "168 Xiahao Street",
      "city": "Chongqing",
      "state": "Chongqing",
      "zipCode": "400060"
    },
    {
      "address": "1 Quancheng Road",
      "city": "Jinan",
      "state": "Shandong",
      "zipCode": "250000"
    },
    {
      "address": "1 Zhongshan Road",
      "city": "Qingdao",
      "state": "Shandong",
      "zipCode": "266001"
    },
    {
      "address": "1 May 1st Square",
      "city": "Dalian",
      "state": "Liaoning",
      "zipCode": "116001"
    },
    {
      "address": "1 Zhongshan Square",
      "city": "Xian",
      "state": "Shaanxi",
      "zipCode": "710002"
    },
    {
      "address": "1 Wuyi Road",
      "city": "Changsha",
      "state": "Hunan",
      "zipCode": "410005"
    },
    {
      "address": "1 Zhongshan Road",
      "city": "Xiamen",
      "state": "Fujian",
      "zipCode": "361001"
    },
    {
      "address": "1 East Street",
      "city": "Fuzhou",
      "state": "Fujian",
      "zipCode": "350001"
    },
    {
      "address": "1 Hongqi Street",
      "city": "Harbin",
      "state": "Heilongjiang",
      "zipCode": "150001"
    },
    {
      "address": "1 Renmin Street",
      "city": "Changchun",
      "state": "Jilin",
      "zipCode": "130051"
    },
    {
      "address": "1 Zhongshan Road",
      "city": "Suzhou",
      "state": "Jiangsu",
      "zipCode": "215005"
    },
    {
      "address": "1 Yangtze Road",
      "city": "Wuxi",
      "state": "Jiangsu",
      "zipCode": "214001"
    }
  ],
  "France": [
    {
      "address": "10 Avenue des Champs-Elysees",
      "city": "Paris",
      "state": "Ile-de-France",
      "zipCode": "75008"
    },
    {
      "address": "16 Boulevard Haussmann",
      "city": "Paris",
      "state": "Ile-de-France",
      "zipCode": "75009"
    },
    {
      "address": "20 Rue de la Republique",
      "city": "Lyon",
      "state": "Auvergne-Rhone-Alpes",
      "zipCode": "69002"
    },
    {
      "address": "1 Quai du Port",
      "city": "Marseille",
      "state": "Provence-Alpes-Cote d Azur",
      "zipCode": "13002"
    },
    {
      "address": "12 Place de la Comedie",
      "city": "Montpellier",
      "state": "Occitanie",
      "zipCode": "34000"
    },
    {
      "address": "8 Rue Sainte-Catherine",
      "city": "Bordeaux",
      "state": "Nouvelle-Aquitaine",
      "zipCode": "33000"
    },
    {
      "address": "2 Place du Capitole",
      "city": "Toulouse",
      "state": "Occitanie",
      "zipCode": "31000"
    },
    {
      "address": "5 Rue Faidherbe",
      "city": "Lille",
      "state": "Hauts-de-France",
      "zipCode": "59000"
    },
    {
      "address": "3 Rue du Dome",
      "city": "Strasbourg",
      "state": "Grand Est",
      "zipCode": "67000"
    },
    {
      "address": "7 Avenue Jean Medecin",
      "city": "Nice",
      "state": "Provence-Alpes-Cote d Azur",
      "zipCode": "06000"
    },
    {
      "address": "1396 Avenue des Champs-Elysees",
      "city": "Paris",
      "state": "Ile-de-France",
      "zipCode": "75008"
    },
    {
      "address": "922 Avenue des Champs-Elysees",
      "city": "Paris",
      "state": "Ile-de-France",
      "zipCode": "75008"
    },
    {
      "address": "1476 Boulevard Haussmann",
      "city": "Paris",
      "state": "Ile-de-France",
      "zipCode": "75009"
    },
    {
      "address": "427 Boulevard Haussmann",
      "city": "Paris",
      "state": "Ile-de-France",
      "zipCode": "75009"
    },
    {
      "address": "586 Rue de la Republique",
      "city": "Lyon",
      "state": "Auvergne-Rhone-Alpes",
      "zipCode": "69002"
    },
    {
      "address": "776 Rue de la Republique",
      "city": "Lyon",
      "state": "Auvergne-Rhone-Alpes",
      "zipCode": "69002"
    },
    {
      "address": "1059 Quai du Port",
      "city": "Marseille",
      "state": "Provence-Alpes-Cote d Azur",
      "zipCode": "13002"
    },
    {
      "address": "171 Quai du Port",
      "city": "Marseille",
      "state": "Provence-Alpes-Cote d Azur",
      "zipCode": "13002"
    },
    {
      "address": "1050 Place de la Comedie",
      "city": "Montpellier",
      "state": "Occitanie",
      "zipCode": "34000"
    },
    {
      "address": "1299 Place de la Comedie",
      "city": "Montpellier",
      "state": "Occitanie",
      "zipCode": "34000"
    },
    {
      "address": "235 Rue Sainte-Catherine",
      "city": "Bordeaux",
      "state": "Nouvelle-Aquitaine",
      "zipCode": "33000"
    },
    {
      "address": "33 Rue Sainte-Catherine",
      "city": "Bordeaux",
      "state": "Nouvelle-Aquitaine",
      "zipCode": "33000"
    },
    {
      "address": "439 Place du Capitole",
      "city": "Toulouse",
      "state": "Occitanie",
      "zipCode": "31000"
    },
    {
      "address": "1316 Place du Capitole",
      "city": "Toulouse",
      "state": "Occitanie",
      "zipCode": "31000"
    },
    {
      "address": "225 Rue Faidherbe",
      "city": "Lille",
      "state": "Hauts-de-France",
      "zipCode": "59000"
    },
    {
      "address": "263 Rue Faidherbe",
      "city": "Lille",
      "state": "Hauts-de-France",
      "zipCode": "59000"
    },
    {
      "address": "691 Rue du Dome",
      "city": "Strasbourg",
      "state": "Grand Est",
      "zipCode": "67000"
    },
    {
      "address": "155 Rue du Dome",
      "city": "Strasbourg",
      "state": "Grand Est",
      "zipCode": "67000"
    },
    {
      "address": "1425 Avenue Jean Medecin",
      "city": "Nice",
      "state": "Provence-Alpes-Cote d Azur",
      "zipCode": "06000"
    },
    {
      "address": "106 Avenue Jean Medecin",
      "city": "Nice",
      "state": "Provence-Alpes-Cote d Azur",
      "zipCode": "06000"
    }
  ],
  "Germany": [
    {
      "address": "Unter den Linden 10",
      "city": "Berlin",
      "state": "Berlin",
      "zipCode": "10117"
    },
    {
      "address": "Friedrichstrasse 100",
      "city": "Berlin",
      "state": "Berlin",
      "zipCode": "10117"
    },
    {
      "address": "Mönckebergstrasse 7",
      "city": "Hamburg",
      "state": "Hamburg",
      "zipCode": "20095"
    },
    {
      "address": "Kaufingerstrasse 15",
      "city": "Munich",
      "state": "Bavaria",
      "zipCode": "80331"
    },
    {
      "address": "Schildergasse 45",
      "city": "Cologne",
      "state": "North Rhine-Westphalia",
      "zipCode": "50667"
    },
    {
      "address": "Zeil 60",
      "city": "Frankfurt",
      "state": "Hesse",
      "zipCode": "60313"
    },
    {
      "address": "Königstrasse 28",
      "city": "Stuttgart",
      "state": "Baden-Württemberg",
      "zipCode": "70173"
    },
    {
      "address": "Königsallee 30",
      "city": "Düsseldorf",
      "state": "North Rhine-Westphalia",
      "zipCode": "40212"
    },
    {
      "address": "Prager Strasse 12",
      "city": "Dresden",
      "state": "Saxony",
      "zipCode": "01069"
    },
    {
      "address": "Petersstrasse 20",
      "city": "Leipzig",
      "state": "Saxony",
      "zipCode": "04109"
    },
    {
      "address": "Unter den Linden 294",
      "city": "Berlin",
      "state": "Berlin",
      "zipCode": "10117"
    },
    {
      "address": "Unter den Linden 1277",
      "city": "Berlin",
      "state": "Berlin",
      "zipCode": "10117"
    },
    {
      "address": "Friedrichstrasse 930",
      "city": "Berlin",
      "state": "Berlin",
      "zipCode": "10117"
    },
    {
      "address": "Friedrichstrasse 870",
      "city": "Berlin",
      "state": "Berlin",
      "zipCode": "10117"
    },
    {
      "address": "Mönckebergstrasse 534",
      "city": "Hamburg",
      "state": "Hamburg",
      "zipCode": "20095"
    },
    {
      "address": "Mönckebergstrasse 668",
      "city": "Hamburg",
      "state": "Hamburg",
      "zipCode": "20095"
    },
    {
      "address": "Kaufingerstrasse 990",
      "city": "Munich",
      "state": "Bavaria",
      "zipCode": "80331"
    },
    {
      "address": "Kaufingerstrasse 1214",
      "city": "Munich",
      "state": "Bavaria",
      "zipCode": "80331"
    },
    {
      "address": "Schildergasse 491",
      "city": "Cologne",
      "state": "North Rhine-Westphalia",
      "zipCode": "50667"
    },
    {
      "address": "Schildergasse 1006",
      "city": "Cologne",
      "state": "North Rhine-Westphalia",
      "zipCode": "50667"
    },
    {
      "address": "Zeil 1410",
      "city": "Frankfurt",
      "state": "Hesse",
      "zipCode": "60313"
    },
    {
      "address": "Zeil 802",
      "city": "Frankfurt",
      "state": "Hesse",
      "zipCode": "60313"
    },
    {
      "address": "Königstrasse 813",
      "city": "Stuttgart",
      "state": "Baden-Württemberg",
      "zipCode": "70173"
    },
    {
      "address": "Königstrasse 384",
      "city": "Stuttgart",
      "state": "Baden-Württemberg",
      "zipCode": "70173"
    },
    {
      "address": "Königsallee 786",
      "city": "Düsseldorf",
      "state": "North Rhine-Westphalia",
      "zipCode": "40212"
    },
    {
      "address": "Königsallee 1406",
      "city": "Düsseldorf",
      "state": "North Rhine-Westphalia",
      "zipCode": "40212"
    },
    {
      "address": "Prager Strasse 400",
      "city": "Dresden",
      "state": "Saxony",
      "zipCode": "01069"
    },
    {
      "address": "Prager Strasse 107",
      "city": "Dresden",
      "state": "Saxony",
      "zipCode": "01069"
    },
    {
      "address": "Petersstrasse 1202",
      "city": "Leipzig",
      "state": "Saxony",
      "zipCode": "04109"
    },
    {
      "address": "Petersstrasse 465",
      "city": "Leipzig",
      "state": "Saxony",
      "zipCode": "04109"
    }
  ],
  "Hong Kong": [
    {
      "address": "1 Connaught Place",
      "city": "Central",
      "state": "Hong Kong Island",
      "zipCode": ""
    },
    {
      "address": "10 Des Voeux Road Central",
      "city": "Central",
      "state": "Hong Kong Island",
      "zipCode": ""
    },
    {
      "address": "18 Salisbury Road",
      "city": "Tsim Sha Tsui",
      "state": "Kowloon",
      "zipCode": ""
    },
    {
      "address": "8 Canton Road",
      "city": "Tsim Sha Tsui",
      "state": "Kowloon",
      "zipCode": ""
    },
    {
      "address": "555 Hennessy Road",
      "city": "Causeway Bay",
      "state": "Hong Kong Island",
      "zipCode": ""
    },
    {
      "address": "388 Prince Edward Road",
      "city": "Kowloon",
      "state": "Kowloon",
      "zipCode": ""
    },
    {
      "address": "99 Queen's Road East",
      "city": "Central",
      "state": "Hong Kong Island",
      "zipCode": ""
    },
    {
      "address": "1 Austin Road West",
      "city": "Tsim Sha Tsui",
      "state": "Kowloon",
      "zipCode": ""
    },
    {
      "address": "12 Sha Tin Centre Street",
      "city": "Sha Tin",
      "state": "New Territories",
      "zipCode": ""
    },
    {
      "address": "33 Canton Road",
      "city": "Tsim Sha Tsui",
      "state": "Kowloon",
      "zipCode": ""
    },
    {
      "address": "971 Connaught Place",
      "city": "Central",
      "state": "Hong Kong Island",
      "zipCode": ""
    },
    {
      "address": "714 Connaught Place",
      "city": "Central",
      "state": "Hong Kong Island",
      "zipCode": ""
    },
    {
      "address": "18 Des Voeux Road Central",
      "city": "Central",
      "state": "Hong Kong Island",
      "zipCode": ""
    },
    {
      "address": "1358 Des Voeux Road Central",
      "city": "Central",
      "state": "Hong Kong Island",
      "zipCode": ""
    },
    {
      "address": "522 Salisbury Road",
      "city": "Tsim Sha Tsui",
      "state": "Kowloon",
      "zipCode": ""
    },
    {
      "address": "301 Salisbury Road",
      "city": "Tsim Sha Tsui",
      "state": "Kowloon",
      "zipCode": ""
    },
    {
      "address": "1459 Canton Road",
      "city": "Tsim Sha Tsui",
      "state": "Kowloon",
      "zipCode": ""
    },
    {
      "address": "824 Canton Road",
      "city": "Tsim Sha Tsui",
      "state": "Kowloon",
      "zipCode": ""
    },
    {
      "address": "96 Hennessy Road",
      "city": "Causeway Bay",
      "state": "Hong Kong Island",
      "zipCode": ""
    },
    {
      "address": "712 Hennessy Road",
      "city": "Causeway Bay",
      "state": "Hong Kong Island",
      "zipCode": ""
    },
    {
      "address": "1175 Prince Edward Road",
      "city": "Kowloon",
      "state": "Kowloon",
      "zipCode": ""
    },
    {
      "address": "1111 Prince Edward Road",
      "city": "Kowloon",
      "state": "Kowloon",
      "zipCode": ""
    },
    {
      "address": "405 Queen's Road East",
      "city": "Central",
      "state": "Hong Kong Island",
      "zipCode": ""
    },
    {
      "address": "69 Queen's Road East",
      "city": "Central",
      "state": "Hong Kong Island",
      "zipCode": ""
    },
    {
      "address": "485 Austin Road West",
      "city": "Tsim Sha Tsui",
      "state": "Kowloon",
      "zipCode": ""
    },
    {
      "address": "547 Austin Road West",
      "city": "Tsim Sha Tsui",
      "state": "Kowloon",
      "zipCode": ""
    },
    {
      "address": "693 Sha Tin Centre Street",
      "city": "Sha Tin",
      "state": "New Territories",
      "zipCode": ""
    },
    {
      "address": "1143 Sha Tin Centre Street",
      "city": "Sha Tin",
      "state": "New Territories",
      "zipCode": ""
    },
    {
      "address": "1309 Canton Road",
      "city": "Tsim Sha Tsui",
      "state": "Kowloon",
      "zipCode": ""
    },
    {
      "address": "601 Canton Road",
      "city": "Tsim Sha Tsui",
      "state": "Kowloon",
      "zipCode": ""
    }
  ],
  "India": [
    {
      "address": "12 MG Road",
      "city": "Mumbai",
      "state": "Maharashtra",
      "zipCode": "400001"
    },
    {
      "address": "45 Linking Road",
      "city": "Mumbai",
      "state": "Maharashtra",
      "zipCode": "400050"
    },
    {
      "address": "8 Connaught Place",
      "city": "Delhi",
      "state": "Delhi",
      "zipCode": "110001"
    },
    {
      "address": "120 Janpath",
      "city": "Delhi",
      "state": "Delhi",
      "zipCode": "110011"
    },
    {
      "address": "50 Brigade Road",
      "city": "Bangalore",
      "state": "Karnataka",
      "zipCode": "560001"
    },
    {
      "address": "18 Park Street",
      "city": "Kolkata",
      "state": "West Bengal",
      "zipCode": "700016"
    },
    {
      "address": "32 Anna Salai",
      "city": "Chennai",
      "state": "Tamil Nadu",
      "zipCode": "600002"
    },
    {
      "address": "5 Residency Road",
      "city": "Hyderabad",
      "state": "Telangana",
      "zipCode": "500001"
    },
    {
      "address": "66 Ashram Road",
      "city": "Ahmedabad",
      "state": "Gujarat",
      "zipCode": "380009"
    },
    {
      "address": "14 FC Road",
      "city": "Pune",
      "state": "Maharashtra",
      "zipCode": "411004"
    },
    {
      "address": "840 MG Road",
      "city": "Mumbai",
      "state": "Maharashtra",
      "zipCode": "400001"
    },
    {
      "address": "917 MG Road",
      "city": "Mumbai",
      "state": "Maharashtra",
      "zipCode": "400001"
    },
    {
      "address": "1453 Linking Road",
      "city": "Mumbai",
      "state": "Maharashtra",
      "zipCode": "400050"
    },
    {
      "address": "379 Linking Road",
      "city": "Mumbai",
      "state": "Maharashtra",
      "zipCode": "400050"
    },
    {
      "address": "1319 Connaught Place",
      "city": "Delhi",
      "state": "Delhi",
      "zipCode": "110001"
    },
    {
      "address": "869 Connaught Place",
      "city": "Delhi",
      "state": "Delhi",
      "zipCode": "110001"
    },
    {
      "address": "969 Janpath",
      "city": "Delhi",
      "state": "Delhi",
      "zipCode": "110011"
    },
    {
      "address": "130 Janpath",
      "city": "Delhi",
      "state": "Delhi",
      "zipCode": "110011"
    },
    {
      "address": "273 Brigade Road",
      "city": "Bangalore",
      "state": "Karnataka",
      "zipCode": "560001"
    },
    {
      "address": "1302 Brigade Road",
      "city": "Bangalore",
      "state": "Karnataka",
      "zipCode": "560001"
    },
    {
      "address": "157 Park Street",
      "city": "Kolkata",
      "state": "West Bengal",
      "zipCode": "700016"
    },
    {
      "address": "171 Park Street",
      "city": "Kolkata",
      "state": "West Bengal",
      "zipCode": "700016"
    },
    {
      "address": "277 Anna Salai",
      "city": "Chennai",
      "state": "Tamil Nadu",
      "zipCode": "600002"
    },
    {
      "address": "78 Anna Salai",
      "city": "Chennai",
      "state": "Tamil Nadu",
      "zipCode": "600002"
    },
    {
      "address": "1431 Residency Road",
      "city": "Hyderabad",
      "state": "Telangana",
      "zipCode": "500001"
    },
    {
      "address": "1101 Residency Road",
      "city": "Hyderabad",
      "state": "Telangana",
      "zipCode": "500001"
    },
    {
      "address": "1466 Ashram Road",
      "city": "Ahmedabad",
      "state": "Gujarat",
      "zipCode": "380009"
    },
    {
      "address": "126 Ashram Road",
      "city": "Ahmedabad",
      "state": "Gujarat",
      "zipCode": "380009"
    },
    {
      "address": "262 FC Road",
      "city": "Pune",
      "state": "Maharashtra",
      "zipCode": "411004"
    },
    {
      "address": "512 FC Road",
      "city": "Pune",
      "state": "Maharashtra",
      "zipCode": "411004"
    }
  ],
  "Italy": [
    {
      "address": "Via del Corso 120",
      "city": "Rome",
      "state": "Lazio",
      "zipCode": "00186"
    },
    {
      "address": "Via Nazionale 45",
      "city": "Rome",
      "state": "Lazio",
      "zipCode": "00184"
    },
    {
      "address": "Via Torino 61",
      "city": "Milan",
      "state": "Lombardy",
      "zipCode": "20123"
    },
    {
      "address": "Corso Buenos Aires 15",
      "city": "Milan",
      "state": "Lombardy",
      "zipCode": "20124"
    },
    {
      "address": "Via Toledo 220",
      "city": "Naples",
      "state": "Campania",
      "zipCode": "80134"
    },
    {
      "address": "Via Roma 90",
      "city": "Turin",
      "state": "Piedmont",
      "zipCode": "10121"
    },
    {
      "address": "Via Maqueda 75",
      "city": "Palermo",
      "state": "Sicily",
      "zipCode": "90133"
    },
    {
      "address": "Via XX Settembre 40",
      "city": "Genoa",
      "state": "Liguria",
      "zipCode": "16121"
    },
    {
      "address": "Via Rizzoli 12",
      "city": "Bologna",
      "state": "Emilia-Romagna",
      "zipCode": "40125"
    },
    {
      "address": "Via de Tornabuoni 18",
      "city": "Florence",
      "state": "Tuscany",
      "zipCode": "50123"
    },
    {
      "address": "Via del Corso 1046",
      "city": "Rome",
      "state": "Lazio",
      "zipCode": "00186"
    },
    {
      "address": "Via del Corso 169",
      "city": "Rome",
      "state": "Lazio",
      "zipCode": "00186"
    },
    {
      "address": "Via Nazionale 1020",
      "city": "Rome",
      "state": "Lazio",
      "zipCode": "00184"
    },
    {
      "address": "Via Nazionale 300",
      "city": "Rome",
      "state": "Lazio",
      "zipCode": "00184"
    },
    {
      "address": "Via Torino 832",
      "city": "Milan",
      "state": "Lombardy",
      "zipCode": "20123"
    },
    {
      "address": "Via Torino 212",
      "city": "Milan",
      "state": "Lombardy",
      "zipCode": "20123"
    },
    {
      "address": "Corso Buenos Aires 669",
      "city": "Milan",
      "state": "Lombardy",
      "zipCode": "20124"
    },
    {
      "address": "Corso Buenos Aires 812",
      "city": "Milan",
      "state": "Lombardy",
      "zipCode": "20124"
    },
    {
      "address": "Via Toledo 958",
      "city": "Naples",
      "state": "Campania",
      "zipCode": "80134"
    },
    {
      "address": "Via Toledo 607",
      "city": "Naples",
      "state": "Campania",
      "zipCode": "80134"
    },
    {
      "address": "Via Roma 77",
      "city": "Turin",
      "state": "Piedmont",
      "zipCode": "10121"
    },
    {
      "address": "Via Roma 798",
      "city": "Turin",
      "state": "Piedmont",
      "zipCode": "10121"
    },
    {
      "address": "Via Maqueda 900",
      "city": "Palermo",
      "state": "Sicily",
      "zipCode": "90133"
    },
    {
      "address": "Via Maqueda 346",
      "city": "Palermo",
      "state": "Sicily",
      "zipCode": "90133"
    },
    {
      "address": "Via XX Settembre 1273",
      "city": "Genoa",
      "state": "Liguria",
      "zipCode": "16121"
    },
    {
      "address": "Via XX Settembre 1130",
      "city": "Genoa",
      "state": "Liguria",
      "zipCode": "16121"
    },
    {
      "address": "Via Rizzoli 359",
      "city": "Bologna",
      "state": "Emilia-Romagna",
      "zipCode": "40125"
    },
    {
      "address": "Via Rizzoli 798",
      "city": "Bologna",
      "state": "Emilia-Romagna",
      "zipCode": "40125"
    },
    {
      "address": "Via de Tornabuoni 805",
      "city": "Florence",
      "state": "Tuscany",
      "zipCode": "50123"
    },
    {
      "address": "Via de Tornabuoni 529",
      "city": "Florence",
      "state": "Tuscany",
      "zipCode": "50123"
    }
  ],
  "Japan": [
    {
      "address": "1-1 Chiyoda",
      "city": "Tokyo",
      "state": "Tokyo",
      "zipCode": "100-8111"
    },
    {
      "address": "2-8-1 Nishi-Shinjuku",
      "city": "Tokyo",
      "state": "Tokyo",
      "zipCode": "163-8001"
    },
    {
      "address": "3-1-1 Umeda",
      "city": "Osaka",
      "state": "Osaka",
      "zipCode": "530-0001"
    },
    {
      "address": "1-2-3 Minato Mirai",
      "city": "Yokohama",
      "state": "Kanagawa",
      "zipCode": "220-0012"
    },
    {
      "address": "1-1 Sakae",
      "city": "Nagoya",
      "state": "Aichi",
      "zipCode": "460-0008"
    },
    {
      "address": "2-5 Kita 5 Jo Nishi",
      "city": "Sapporo",
      "state": "Hokkaido",
      "zipCode": "060-0005"
    },
    {
      "address": "1-1 Tenjin",
      "city": "Fukuoka",
      "state": "Fukuoka",
      "zipCode": "810-0001"
    },
    {
      "address": "2-2-1 Sannomiya",
      "city": "Kobe",
      "state": "Hyogo",
      "zipCode": "650-0021"
    },
    {
      "address": "1-1 Shijo-dori",
      "city": "Kyoto",
      "state": "Kyoto",
      "zipCode": "600-8001"
    },
    {
      "address": "1-3-1 Sendai Aoba",
      "city": "Sendai",
      "state": "Miyagi",
      "zipCode": "980-0811"
    },
    {
      "address": "1-6-5 Marunouchi",
      "city": "Tokyo",
      "state": "Tokyo",
      "zipCode": "100-0005"
    },
    {
      "address": "1-1-1 Shibuya",
      "city": "Tokyo",
      "state": "Tokyo",
      "zipCode": "150-0002"
    },
    {
      "address": "1-7-1 Dotonbori",
      "city": "Osaka",
      "state": "Osaka",
      "zipCode": "542-0071"
    },
    {
      "address": "2-1-1 Naka-ku",
      "city": "Yokohama",
      "state": "Kanagawa",
      "zipCode": "231-0005"
    },
    {
      "address": "3-15-1 Meieki",
      "city": "Nagoya",
      "state": "Aichi",
      "zipCode": "450-0002"
    },
    {
      "address": "1-1 Odori Nishi",
      "city": "Sapporo",
      "state": "Hokkaido",
      "zipCode": "060-0042"
    },
    {
      "address": "2-1-1 Hakata-eki",
      "city": "Fukuoka",
      "state": "Fukuoka",
      "zipCode": "812-0012"
    },
    {
      "address": "1-1-1 Motomachi",
      "city": "Kobe",
      "state": "Hyogo",
      "zipCode": "650-0022"
    },
    {
      "address": "2-1 Kawaramachi",
      "city": "Kyoto",
      "state": "Kyoto",
      "zipCode": "600-8009"
    },
    {
      "address": "1-1-1 Chuo",
      "city": "Sendai",
      "state": "Miyagi",
      "zipCode": "980-0021"
    },
    {
      "address": "1-1 Ekimae-dori",
      "city": "Hiroshima",
      "state": "Hiroshima",
      "zipCode": "730-0031"
    },
    {
      "address": "1-1 Bandai",
      "city": "Niigata",
      "state": "Niigata",
      "zipCode": "950-0088"
    },
    {
      "address": "1-1 Otemachi",
      "city": "Kanazawa",
      "state": "Ishikawa",
      "zipCode": "920-0901"
    },
    {
      "address": "1-1 Chuo-dori",
      "city": "Okayama",
      "state": "Okayama",
      "zipCode": "700-0021"
    },
    {
      "address": "1-1 Minami-machi",
      "city": "Takamatsu",
      "state": "Kagawa",
      "zipCode": "760-0017"
    },
    {
      "address": "1-1 Matsuyama-jo",
      "city": "Matsuyama",
      "state": "Ehime",
      "zipCode": "790-0001"
    },
    {
      "address": "1-1 Nishi-dori",
      "city": "Kumamoto",
      "state": "Kumamoto",
      "zipCode": "860-0806"
    },
    {
      "address": "1-1 Kokusai-dori",
      "city": "Naha",
      "state": "Okinawa",
      "zipCode": "900-0013"
    },
    {
      "address": "1-1 Chuo",
      "city": "Shizuoka",
      "state": "Shizuoka",
      "zipCode": "420-0851"
    },
    {
      "address": "1-1 Honmachi",
      "city": "Nagasaki",
      "state": "Nagasaki",
      "zipCode": "850-0012"
    }
  ],
  "Mexico": [
    {
      "address": "Avenida Paseo de la Reforma 222",
      "city": "Mexico City",
      "state": "Mexico City",
      "zipCode": "06600"
    },
    {
      "address": "Calle Madero 10",
      "city": "Mexico City",
      "state": "Mexico City",
      "zipCode": "06000"
    },
    {
      "address": "Avenida Juarez 99",
      "city": "Guadalajara",
      "state": "Jalisco",
      "zipCode": "44100"
    },
    {
      "address": "Calle Morelos 120",
      "city": "Guadalajara",
      "state": "Jalisco",
      "zipCode": "44160"
    },
    {
      "address": "Avenida Constitucion 400",
      "city": "Monterrey",
      "state": "Nuevo Leon",
      "zipCode": "64000"
    },
    {
      "address": "Calle 5 de Mayo 88",
      "city": "Puebla",
      "state": "Puebla",
      "zipCode": "72000"
    },
    {
      "address": "Avenida Revolucion 1550",
      "city": "Tijuana",
      "state": "Baja California",
      "zipCode": "22000"
    },
    {
      "address": "Boulevard Kukulkan 31",
      "city": "Cancun",
      "state": "Quintana Roo",
      "zipCode": "77500"
    },
    {
      "address": "Avenida Universidad 300",
      "city": "Mexico City",
      "state": "Mexico City",
      "zipCode": "04360"
    },
    {
      "address": "Avenida Hidalgo 55",
      "city": "Monterrey",
      "state": "Nuevo Leon",
      "zipCode": "64010"
    },
    {
      "address": "Avenida Paseo de la Reforma 780",
      "city": "Mexico City",
      "state": "Mexico City",
      "zipCode": "06600"
    },
    {
      "address": "Avenida Paseo de la Reforma 532",
      "city": "Mexico City",
      "state": "Mexico City",
      "zipCode": "06600"
    },
    {
      "address": "Calle Madero 879",
      "city": "Mexico City",
      "state": "Mexico City",
      "zipCode": "06000"
    },
    {
      "address": "Calle Madero 989",
      "city": "Mexico City",
      "state": "Mexico City",
      "zipCode": "06000"
    },
    {
      "address": "Avenida Juarez 836",
      "city": "Guadalajara",
      "state": "Jalisco",
      "zipCode": "44100"
    },
    {
      "address": "Avenida Juarez 1029",
      "city": "Guadalajara",
      "state": "Jalisco",
      "zipCode": "44100"
    },
    {
      "address": "Calle Morelos 707",
      "city": "Guadalajara",
      "state": "Jalisco",
      "zipCode": "44160"
    },
    {
      "address": "Calle Morelos 795",
      "city": "Guadalajara",
      "state": "Jalisco",
      "zipCode": "44160"
    },
    {
      "address": "Avenida Constitucion 1356",
      "city": "Monterrey",
      "state": "Nuevo Leon",
      "zipCode": "64000"
    },
    {
      "address": "Avenida Constitucion 41",
      "city": "Monterrey",
      "state": "Nuevo Leon",
      "zipCode": "64000"
    },
    {
      "address": "Calle 5 de Mayo 1088",
      "city": "Puebla",
      "state": "Puebla",
      "zipCode": "72000"
    },
    {
      "address": "Calle 5 de Mayo 1463",
      "city": "Puebla",
      "state": "Puebla",
      "zipCode": "72000"
    },
    {
      "address": "Avenida Revolucion 347",
      "city": "Tijuana",
      "state": "Baja California",
      "zipCode": "22000"
    },
    {
      "address": "Avenida Revolucion 1031",
      "city": "Tijuana",
      "state": "Baja California",
      "zipCode": "22000"
    },
    {
      "address": "Boulevard Kukulkan 1002",
      "city": "Cancun",
      "state": "Quintana Roo",
      "zipCode": "77500"
    },
    {
      "address": "Boulevard Kukulkan 943",
      "city": "Cancun",
      "state": "Quintana Roo",
      "zipCode": "77500"
    },
    {
      "address": "Avenida Universidad 57",
      "city": "Mexico City",
      "state": "Mexico City",
      "zipCode": "04360"
    },
    {
      "address": "Avenida Universidad 556",
      "city": "Mexico City",
      "state": "Mexico City",
      "zipCode": "04360"
    },
    {
      "address": "Avenida Hidalgo 459",
      "city": "Monterrey",
      "state": "Nuevo Leon",
      "zipCode": "64010"
    },
    {
      "address": "Avenida Hidalgo 834",
      "city": "Monterrey",
      "state": "Nuevo Leon",
      "zipCode": "64010"
    }
  ],
  "Netherlands": [
    {
      "address": "Damrak 1",
      "city": "Amsterdam",
      "state": "North Holland",
      "zipCode": "1012LG"
    },
    {
      "address": "Kalverstraat 25",
      "city": "Amsterdam",
      "state": "North Holland",
      "zipCode": "1012NX"
    },
    {
      "address": "Coolsingel 100",
      "city": "Rotterdam",
      "state": "South Holland",
      "zipCode": "3012AG"
    },
    {
      "address": "Lijnbaan 1",
      "city": "Rotterdam",
      "state": "South Holland",
      "zipCode": "3012EK"
    },
    {
      "address": "Vredenburg 40",
      "city": "Utrecht",
      "state": "Utrecht",
      "zipCode": "3511BD"
    },
    {
      "address": "Grote Markt 1",
      "city": "Groningen",
      "state": "Groningen",
      "zipCode": "9712HN"
    },
    {
      "address": "Markt 10",
      "city": "Eindhoven",
      "state": "North Brabant",
      "zipCode": "5611EC"
    },
    {
      "address": "Spuistraat 200",
      "city": "The Hague",
      "state": "South Holland",
      "zipCode": "2511BW"
    },
    {
      "address": "Stationsplein 45",
      "city": "Arnhem",
      "state": "Gelderland",
      "zipCode": "6811KG"
    },
    {
      "address": "Mariastraat 11",
      "city": "Haarlem",
      "state": "North Holland",
      "zipCode": "2011LP"
    },
    {
      "address": "Damrak 1159",
      "city": "Amsterdam",
      "state": "North Holland",
      "zipCode": "1012LG"
    },
    {
      "address": "Damrak 444",
      "city": "Amsterdam",
      "state": "North Holland",
      "zipCode": "1012LG"
    },
    {
      "address": "Kalverstraat 1341",
      "city": "Amsterdam",
      "state": "North Holland",
      "zipCode": "1012NX"
    },
    {
      "address": "Kalverstraat 227",
      "city": "Amsterdam",
      "state": "North Holland",
      "zipCode": "1012NX"
    },
    {
      "address": "Coolsingel 1435",
      "city": "Rotterdam",
      "state": "South Holland",
      "zipCode": "3012AG"
    },
    {
      "address": "Coolsingel 289",
      "city": "Rotterdam",
      "state": "South Holland",
      "zipCode": "3012AG"
    },
    {
      "address": "Lijnbaan 839",
      "city": "Rotterdam",
      "state": "South Holland",
      "zipCode": "3012EK"
    },
    {
      "address": "Lijnbaan 1168",
      "city": "Rotterdam",
      "state": "South Holland",
      "zipCode": "3012EK"
    },
    {
      "address": "Vredenburg 1349",
      "city": "Utrecht",
      "state": "Utrecht",
      "zipCode": "3511BD"
    },
    {
      "address": "Vredenburg 237",
      "city": "Utrecht",
      "state": "Utrecht",
      "zipCode": "3511BD"
    },
    {
      "address": "Grote Markt 884",
      "city": "Groningen",
      "state": "Groningen",
      "zipCode": "9712HN"
    },
    {
      "address": "Grote Markt 3",
      "city": "Groningen",
      "state": "Groningen",
      "zipCode": "9712HN"
    },
    {
      "address": "Markt 1260",
      "city": "Eindhoven",
      "state": "North Brabant",
      "zipCode": "5611EC"
    },
    {
      "address": "Markt 873",
      "city": "Eindhoven",
      "state": "North Brabant",
      "zipCode": "5611EC"
    },
    {
      "address": "Spuistraat 306",
      "city": "The Hague",
      "state": "South Holland",
      "zipCode": "2511BW"
    },
    {
      "address": "Spuistraat 1146",
      "city": "The Hague",
      "state": "South Holland",
      "zipCode": "2511BW"
    },
    {
      "address": "Stationsplein 1430",
      "city": "Arnhem",
      "state": "Gelderland",
      "zipCode": "6811KG"
    },
    {
      "address": "Stationsplein 24",
      "city": "Arnhem",
      "state": "Gelderland",
      "zipCode": "6811KG"
    },
    {
      "address": "Mariastraat 932",
      "city": "Haarlem",
      "state": "North Holland",
      "zipCode": "2011LP"
    },
    {
      "address": "Mariastraat 1014",
      "city": "Haarlem",
      "state": "North Holland",
      "zipCode": "2011LP"
    }
  ],
  "Russia": [
    {
      "address": "1 Tverskaya Street",
      "city": "Moscow",
      "state": "Moscow",
      "zipCode": "125009"
    },
    {
      "address": "15 Arbat Street",
      "city": "Moscow",
      "state": "Moscow",
      "zipCode": "119019"
    },
    {
      "address": "100 Nevsky Prospect",
      "city": "Saint Petersburg",
      "state": "Saint Petersburg",
      "zipCode": "191025"
    },
    {
      "address": "20 Liteyny Avenue",
      "city": "Saint Petersburg",
      "state": "Saint Petersburg",
      "zipCode": "191014"
    },
    {
      "address": "8 Krasny Prospekt",
      "city": "Novosibirsk",
      "state": "Novosibirsk Oblast",
      "zipCode": "630099"
    },
    {
      "address": "35 Lenina Avenue",
      "city": "Yekaterinburg",
      "state": "Sverdlovsk Oblast",
      "zipCode": "620014"
    },
    {
      "address": "12 Bauman Street",
      "city": "Kazan",
      "state": "Tatarstan",
      "zipCode": "420111"
    },
    {
      "address": "60 Bolshaya Pokrovskaya",
      "city": "Nizhny Novgorod",
      "state": "Nizhny Novgorod Oblast",
      "zipCode": "603005"
    },
    {
      "address": "22 Kirovka Street",
      "city": "Chelyabinsk",
      "state": "Chelyabinsk Oblast",
      "zipCode": "454091"
    },
    {
      "address": "44 Leningradskaya Street",
      "city": "Samara",
      "state": "Samara Oblast",
      "zipCode": "443099"
    },
    {
      "address": "226 Tverskaya Street",
      "city": "Moscow",
      "state": "Moscow",
      "zipCode": "125009"
    },
    {
      "address": "639 Tverskaya Street",
      "city": "Moscow",
      "state": "Moscow",
      "zipCode": "125009"
    },
    {
      "address": "751 Arbat Street",
      "city": "Moscow",
      "state": "Moscow",
      "zipCode": "119019"
    },
    {
      "address": "804 Arbat Street",
      "city": "Moscow",
      "state": "Moscow",
      "zipCode": "119019"
    },
    {
      "address": "573 Nevsky Prospect",
      "city": "Saint Petersburg",
      "state": "Saint Petersburg",
      "zipCode": "191025"
    },
    {
      "address": "1383 Nevsky Prospect",
      "city": "Saint Petersburg",
      "state": "Saint Petersburg",
      "zipCode": "191025"
    },
    {
      "address": "317 Liteyny Avenue",
      "city": "Saint Petersburg",
      "state": "Saint Petersburg",
      "zipCode": "191014"
    },
    {
      "address": "851 Liteyny Avenue",
      "city": "Saint Petersburg",
      "state": "Saint Petersburg",
      "zipCode": "191014"
    },
    {
      "address": "660 Krasny Prospekt",
      "city": "Novosibirsk",
      "state": "Novosibirsk Oblast",
      "zipCode": "630099"
    },
    {
      "address": "429 Krasny Prospekt",
      "city": "Novosibirsk",
      "state": "Novosibirsk Oblast",
      "zipCode": "630099"
    },
    {
      "address": "614 Lenina Avenue",
      "city": "Yekaterinburg",
      "state": "Sverdlovsk Oblast",
      "zipCode": "620014"
    },
    {
      "address": "1303 Lenina Avenue",
      "city": "Yekaterinburg",
      "state": "Sverdlovsk Oblast",
      "zipCode": "620014"
    },
    {
      "address": "841 Bauman Street",
      "city": "Kazan",
      "state": "Tatarstan",
      "zipCode": "420111"
    },
    {
      "address": "1283 Bauman Street",
      "city": "Kazan",
      "state": "Tatarstan",
      "zipCode": "420111"
    },
    {
      "address": "1268 Bolshaya Pokrovskaya",
      "city": "Nizhny Novgorod",
      "state": "Nizhny Novgorod Oblast",
      "zipCode": "603005"
    },
    {
      "address": "750 Bolshaya Pokrovskaya",
      "city": "Nizhny Novgorod",
      "state": "Nizhny Novgorod Oblast",
      "zipCode": "603005"
    },
    {
      "address": "838 Kirovka Street",
      "city": "Chelyabinsk",
      "state": "Chelyabinsk Oblast",
      "zipCode": "454091"
    },
    {
      "address": "776 Kirovka Street",
      "city": "Chelyabinsk",
      "state": "Chelyabinsk Oblast",
      "zipCode": "454091"
    },
    {
      "address": "898 Leningradskaya Street",
      "city": "Samara",
      "state": "Samara Oblast",
      "zipCode": "443099"
    },
    {
      "address": "1364 Leningradskaya Street",
      "city": "Samara",
      "state": "Samara Oblast",
      "zipCode": "443099"
    }
  ],
  "Singapore": [
    {
      "address": "1 Raffles Place",
      "city": "Singapore",
      "state": "Central Region",
      "zipCode": "048616"
    },
    {
      "address": "2 Orchard Turn",
      "city": "Singapore",
      "state": "Central Region",
      "zipCode": "238801"
    },
    {
      "address": "10 Bayfront Avenue",
      "city": "Singapore",
      "state": "Central Region",
      "zipCode": "018956"
    },
    {
      "address": "50 Jurong Gateway Road",
      "city": "Jurong East",
      "state": "West Region",
      "zipCode": "608549"
    },
    {
      "address": "21 Tampines Avenue 1",
      "city": "Tampines",
      "state": "East Region",
      "zipCode": "529757"
    },
    {
      "address": "1 Woodlands Square",
      "city": "Woodlands",
      "state": "North Region",
      "zipCode": "738099"
    },
    {
      "address": "311 New Upper Changi Road",
      "city": "Bedok",
      "state": "East Region",
      "zipCode": "467360"
    },
    {
      "address": "53 Ang Mo Kio Avenue 3",
      "city": "Ang Mo Kio",
      "state": "North-East Region",
      "zipCode": "569933"
    },
    {
      "address": "200 Victoria Street",
      "city": "Singapore",
      "state": "Central Region",
      "zipCode": "188021"
    },
    {
      "address": "30 Bencoolen Street",
      "city": "Singapore",
      "state": "Central Region",
      "zipCode": "189621"
    },
    {
      "address": "128 Raffles Place",
      "city": "Singapore",
      "state": "Central Region",
      "zipCode": "048616"
    },
    {
      "address": "161 Raffles Place",
      "city": "Singapore",
      "state": "Central Region",
      "zipCode": "048616"
    },
    {
      "address": "341 Orchard Turn",
      "city": "Singapore",
      "state": "Central Region",
      "zipCode": "238801"
    },
    {
      "address": "716 Orchard Turn",
      "city": "Singapore",
      "state": "Central Region",
      "zipCode": "238801"
    },
    {
      "address": "683 Bayfront Avenue",
      "city": "Singapore",
      "state": "Central Region",
      "zipCode": "018956"
    },
    {
      "address": "1359 Bayfront Avenue",
      "city": "Singapore",
      "state": "Central Region",
      "zipCode": "018956"
    },
    {
      "address": "273 Jurong Gateway Road",
      "city": "Jurong East",
      "state": "West Region",
      "zipCode": "608549"
    },
    {
      "address": "647 Jurong Gateway Road",
      "city": "Jurong East",
      "state": "West Region",
      "zipCode": "608549"
    },
    {
      "address": "728 Tampines Avenue 1",
      "city": "Tampines",
      "state": "East Region",
      "zipCode": "529757"
    },
    {
      "address": "1214 Tampines Avenue 1",
      "city": "Tampines",
      "state": "East Region",
      "zipCode": "529757"
    },
    {
      "address": "561 Woodlands Square",
      "city": "Woodlands",
      "state": "North Region",
      "zipCode": "738099"
    },
    {
      "address": "822 Woodlands Square",
      "city": "Woodlands",
      "state": "North Region",
      "zipCode": "738099"
    },
    {
      "address": "997 New Upper Changi Road",
      "city": "Bedok",
      "state": "East Region",
      "zipCode": "467360"
    },
    {
      "address": "1173 New Upper Changi Road",
      "city": "Bedok",
      "state": "East Region",
      "zipCode": "467360"
    },
    {
      "address": "374 Ang Mo Kio Avenue 3",
      "city": "Ang Mo Kio",
      "state": "North-East Region",
      "zipCode": "569933"
    },
    {
      "address": "692 Ang Mo Kio Avenue 3",
      "city": "Ang Mo Kio",
      "state": "North-East Region",
      "zipCode": "569933"
    },
    {
      "address": "268 Victoria Street",
      "city": "Singapore",
      "state": "Central Region",
      "zipCode": "188021"
    },
    {
      "address": "888 Victoria Street",
      "city": "Singapore",
      "state": "Central Region",
      "zipCode": "188021"
    },
    {
      "address": "1299 Bencoolen Street",
      "city": "Singapore",
      "state": "Central Region",
      "zipCode": "189621"
    },
    {
      "address": "450 Bencoolen Street",
      "city": "Singapore",
      "state": "Central Region",
      "zipCode": "189621"
    }
  ],
  "South Korea": [
    {
      "address": "110 Sejong-daero",
      "city": "Seoul",
      "state": "Seoul",
      "zipCode": "04524"
    },
    {
      "address": "231 Teheran-ro",
      "city": "Seoul",
      "state": "Seoul",
      "zipCode": "06142"
    },
    {
      "address": "1 Jungang-daero",
      "city": "Busan",
      "state": "Busan",
      "zipCode": "48939"
    },
    {
      "address": "160 Incheon-daero",
      "city": "Incheon",
      "state": "Incheon",
      "zipCode": "22382"
    },
    {
      "address": "100 Dalseong-ro",
      "city": "Daegu",
      "state": "Daegu",
      "zipCode": "41911"
    },
    {
      "address": "101 Dunsan-ro",
      "city": "Daejeon",
      "state": "Daejeon",
      "zipCode": "35242"
    },
    {
      "address": "50 Geumnam-ro",
      "city": "Gwangju",
      "state": "Gwangju",
      "zipCode": "61482"
    },
    {
      "address": "85 Gwonseon-ro",
      "city": "Suwon",
      "state": "Gyeonggi",
      "zipCode": "16488"
    },
    {
      "address": "22 Namgu-ro",
      "city": "Ulsan",
      "state": "Ulsan",
      "zipCode": "44675"
    },
    {
      "address": "12 Changwon-daero",
      "city": "Changwon",
      "state": "South Gyeongsang",
      "zipCode": "51435"
    },
    {
      "address": "26 Eulji-ro",
      "city": "Seoul",
      "state": "Seoul",
      "zipCode": "04533"
    },
    {
      "address": "517 Yeongdong-daero",
      "city": "Seoul",
      "state": "Seoul",
      "zipCode": "06164"
    },
    {
      "address": "100 Gwangalli Beach-ro",
      "city": "Busan",
      "state": "Busan",
      "zipCode": "48225"
    },
    {
      "address": "12 Songdo-dong",
      "city": "Incheon",
      "state": "Incheon",
      "zipCode": "21999"
    },
    {
      "address": "11 Dongseong-ro",
      "city": "Daegu",
      "state": "Daegu",
      "zipCode": "41941"
    },
    {
      "address": "1 Expo-ro",
      "city": "Daejeon",
      "state": "Daejeon",
      "zipCode": "34126"
    },
    {
      "address": "200 Chungjang-ro",
      "city": "Gwangju",
      "state": "Gwangju",
      "zipCode": "61475"
    },
    {
      "address": "111 Ingye-ro",
      "city": "Suwon",
      "state": "Gyeonggi",
      "zipCode": "16488"
    },
    {
      "address": "55 Samsan-ro",
      "city": "Ulsan",
      "state": "Ulsan",
      "zipCode": "44705"
    },
    {
      "address": "15 Jungang-daero",
      "city": "Changwon",
      "state": "South Gyeongsang",
      "zipCode": "51154"
    },
    {
      "address": "1 Jungang-ro",
      "city": "Jeonju",
      "state": "North Jeolla",
      "zipCode": "54999"
    },
    {
      "address": "10 Jungang-ro",
      "city": "Cheongju",
      "state": "North Chungcheong",
      "zipCode": "28511"
    },
    {
      "address": "20 Jungang-ro",
      "city": "Jeju",
      "state": "Jeju",
      "zipCode": "63219"
    },
    {
      "address": "30 Jungang-daero",
      "city": "Goyang",
      "state": "Gyeonggi",
      "zipCode": "10464"
    },
    {
      "address": "40 Bucheon-ro",
      "city": "Bucheon",
      "state": "Gyeonggi",
      "zipCode": "14547"
    },
    {
      "address": "50 Jungang-ro",
      "city": "Ansan",
      "state": "Gyeonggi",
      "zipCode": "15355"
    },
    {
      "address": "60 Jungang-ro",
      "city": "Cheonan",
      "state": "South Chungcheong",
      "zipCode": "31128"
    },
    {
      "address": "70 Jungang-ro",
      "city": "Pohang",
      "state": "North Gyeongsang",
      "zipCode": "37688"
    },
    {
      "address": "80 Jungang-ro",
      "city": "Gimhae",
      "state": "South Gyeongsang",
      "zipCode": "50936"
    },
    {
      "address": "90 Jungang-ro",
      "city": "Yongin",
      "state": "Gyeonggi",
      "zipCode": "17015"
    }
  ],
  "Spain": [
    {
      "address": "Gran Via 1",
      "city": "Madrid",
      "state": "Madrid",
      "zipCode": "28013"
    },
    {
      "address": "Calle de Alcala 45",
      "city": "Madrid",
      "state": "Madrid",
      "zipCode": "28014"
    },
    {
      "address": "La Rambla 91",
      "city": "Barcelona",
      "state": "Catalonia",
      "zipCode": "08002"
    },
    {
      "address": "Passeig de Gracia 60",
      "city": "Barcelona",
      "state": "Catalonia",
      "zipCode": "08007"
    },
    {
      "address": "Calle Colon 12",
      "city": "Valencia",
      "state": "Valencia",
      "zipCode": "46004"
    },
    {
      "address": "Calle Sierpes 5",
      "city": "Seville",
      "state": "Andalusia",
      "zipCode": "41004"
    },
    {
      "address": "Calle Larios 8",
      "city": "Malaga",
      "state": "Andalusia",
      "zipCode": "29005"
    },
    {
      "address": "Calle Mayor 20",
      "city": "Zaragoza",
      "state": "Aragon",
      "zipCode": "50001"
    },
    {
      "address": "Gran Via Don Diego Lopez de Haro 12",
      "city": "Bilbao",
      "state": "Basque Country",
      "zipCode": "48001"
    },
    {
      "address": "Calle Traperia 3",
      "city": "Murcia",
      "state": "Murcia",
      "zipCode": "30001"
    },
    {
      "address": "Gran Via 1416",
      "city": "Madrid",
      "state": "Madrid",
      "zipCode": "28013"
    },
    {
      "address": "Gran Via 1308",
      "city": "Madrid",
      "state": "Madrid",
      "zipCode": "28013"
    },
    {
      "address": "Calle de Alcala 537",
      "city": "Madrid",
      "state": "Madrid",
      "zipCode": "28014"
    },
    {
      "address": "Calle de Alcala 620",
      "city": "Madrid",
      "state": "Madrid",
      "zipCode": "28014"
    },
    {
      "address": "La Rambla 874",
      "city": "Barcelona",
      "state": "Catalonia",
      "zipCode": "08002"
    },
    {
      "address": "La Rambla 803",
      "city": "Barcelona",
      "state": "Catalonia",
      "zipCode": "08002"
    },
    {
      "address": "Passeig de Gracia 300",
      "city": "Barcelona",
      "state": "Catalonia",
      "zipCode": "08007"
    },
    {
      "address": "Passeig de Gracia 1035",
      "city": "Barcelona",
      "state": "Catalonia",
      "zipCode": "08007"
    },
    {
      "address": "Calle Colon 639",
      "city": "Valencia",
      "state": "Valencia",
      "zipCode": "46004"
    },
    {
      "address": "Calle Colon 1222",
      "city": "Valencia",
      "state": "Valencia",
      "zipCode": "46004"
    },
    {
      "address": "Calle Sierpes 175",
      "city": "Seville",
      "state": "Andalusia",
      "zipCode": "41004"
    },
    {
      "address": "Calle Sierpes 611",
      "city": "Seville",
      "state": "Andalusia",
      "zipCode": "41004"
    },
    {
      "address": "Calle Larios 58",
      "city": "Malaga",
      "state": "Andalusia",
      "zipCode": "29005"
    },
    {
      "address": "Calle Larios 110",
      "city": "Malaga",
      "state": "Andalusia",
      "zipCode": "29005"
    },
    {
      "address": "Calle Mayor 195",
      "city": "Zaragoza",
      "state": "Aragon",
      "zipCode": "50001"
    },
    {
      "address": "Calle Mayor 832",
      "city": "Zaragoza",
      "state": "Aragon",
      "zipCode": "50001"
    },
    {
      "address": "Gran Via Don Diego Lopez de Haro 373",
      "city": "Bilbao",
      "state": "Basque Country",
      "zipCode": "48001"
    },
    {
      "address": "Gran Via Don Diego Lopez de Haro 505",
      "city": "Bilbao",
      "state": "Basque Country",
      "zipCode": "48001"
    },
    {
      "address": "Calle Traperia 653",
      "city": "Murcia",
      "state": "Murcia",
      "zipCode": "30001"
    },
    {
      "address": "Calle Traperia 943",
      "city": "Murcia",
      "state": "Murcia",
      "zipCode": "30001"
    }
  ],
  "Taiwan": [
    {
      "address": "No. 1, Zhongxiao W Rd",
      "city": "Taipei",
      "state": "Taipei City",
      "zipCode": "100"
    },
    {
      "address": "No. 45, Xinyi Rd",
      "city": "Taipei",
      "state": "Taipei City",
      "zipCode": "110"
    },
    {
      "address": "No. 12, Sanduo 4th Rd",
      "city": "Kaohsiung",
      "state": "Kaohsiung City",
      "zipCode": "802"
    },
    {
      "address": "No. 88, Taiwan Blvd",
      "city": "Taichung",
      "state": "Taichung City",
      "zipCode": "400"
    },
    {
      "address": "No. 20, Minsheng Rd",
      "city": "Tainan",
      "state": "Tainan City",
      "zipCode": "700"
    },
    {
      "address": "No. 10, Fuxing Rd",
      "city": "Hsinchu",
      "state": "Hsinchu City",
      "zipCode": "300"
    },
    {
      "address": "No. 66, Zhongshan Rd",
      "city": "Taoyuan",
      "state": "Taoyuan City",
      "zipCode": "330"
    },
    {
      "address": "No. 99, Wenhua Rd",
      "city": "Taipei",
      "state": "Taipei City",
      "zipCode": "105"
    },
    {
      "address": "No. 35, Chenggong Rd",
      "city": "Kaohsiung",
      "state": "Kaohsiung City",
      "zipCode": "801"
    },
    {
      "address": "No. 18, Dadun Rd",
      "city": "Taichung",
      "state": "Taichung City",
      "zipCode": "408"
    },
    {
      "address": "No. 644, Zhongxiao W Rd",
      "city": "Taipei",
      "state": "Taipei City",
      "zipCode": "100"
    },
    {
      "address": "No. 1431, Zhongxiao W Rd",
      "city": "Taipei",
      "state": "Taipei City",
      "zipCode": "100"
    },
    {
      "address": "No. 1474, Xinyi Rd",
      "city": "Taipei",
      "state": "Taipei City",
      "zipCode": "110"
    },
    {
      "address": "No. 1281, Xinyi Rd",
      "city": "Taipei",
      "state": "Taipei City",
      "zipCode": "110"
    },
    {
      "address": "No. 1280, Sanduo 4th Rd",
      "city": "Kaohsiung",
      "state": "Kaohsiung City",
      "zipCode": "802"
    },
    {
      "address": "No. 452, Sanduo 4th Rd",
      "city": "Kaohsiung",
      "state": "Kaohsiung City",
      "zipCode": "802"
    },
    {
      "address": "No. 1045, Taiwan Blvd",
      "city": "Taichung",
      "state": "Taichung City",
      "zipCode": "400"
    },
    {
      "address": "No. 1027, Taiwan Blvd",
      "city": "Taichung",
      "state": "Taichung City",
      "zipCode": "400"
    },
    {
      "address": "No. 1153, Minsheng Rd",
      "city": "Tainan",
      "state": "Tainan City",
      "zipCode": "700"
    },
    {
      "address": "No. 873, Minsheng Rd",
      "city": "Tainan",
      "state": "Tainan City",
      "zipCode": "700"
    },
    {
      "address": "No. 1254, Fuxing Rd",
      "city": "Hsinchu",
      "state": "Hsinchu City",
      "zipCode": "300"
    },
    {
      "address": "No. 662, Fuxing Rd",
      "city": "Hsinchu",
      "state": "Hsinchu City",
      "zipCode": "300"
    },
    {
      "address": "No. 593, Zhongshan Rd",
      "city": "Taoyuan",
      "state": "Taoyuan City",
      "zipCode": "330"
    },
    {
      "address": "No. 533, Zhongshan Rd",
      "city": "Taoyuan",
      "state": "Taoyuan City",
      "zipCode": "330"
    },
    {
      "address": "No. 935, Wenhua Rd",
      "city": "Taipei",
      "state": "Taipei City",
      "zipCode": "105"
    },
    {
      "address": "No. 558, Wenhua Rd",
      "city": "Taipei",
      "state": "Taipei City",
      "zipCode": "105"
    },
    {
      "address": "No. 1082, Chenggong Rd",
      "city": "Kaohsiung",
      "state": "Kaohsiung City",
      "zipCode": "801"
    },
    {
      "address": "No. 11, Chenggong Rd",
      "city": "Kaohsiung",
      "state": "Kaohsiung City",
      "zipCode": "801"
    },
    {
      "address": "No. 1015, Dadun Rd",
      "city": "Taichung",
      "state": "Taichung City",
      "zipCode": "408"
    },
    {
      "address": "No. 520, Dadun Rd",
      "city": "Taichung",
      "state": "Taichung City",
      "zipCode": "408"
    }
  ],
  "United Kingdom": [
    {
      "address": "10 Downing Street",
      "city": "London",
      "state": "Greater London",
      "zipCode": "SW1A 2AA"
    },
    {
      "address": "221B Baker Street",
      "city": "London",
      "state": "Greater London",
      "zipCode": "NW1 6XE"
    },
    {
      "address": "1 Piccadilly",
      "city": "Manchester",
      "state": "Greater Manchester",
      "zipCode": "M1 1RG"
    },
    {
      "address": "45 Deansgate",
      "city": "Manchester",
      "state": "Greater Manchester",
      "zipCode": "M3 2AY"
    },
    {
      "address": "12 New Street",
      "city": "Birmingham",
      "state": "West Midlands",
      "zipCode": "B2 4QA"
    },
    {
      "address": "100 Princes Street",
      "city": "Edinburgh",
      "state": "Scotland",
      "zipCode": "EH2 3AA"
    },
    {
      "address": "8 George Square",
      "city": "Glasgow",
      "state": "Scotland",
      "zipCode": "G2 1DY"
    },
    {
      "address": "30 Park Row",
      "city": "Leeds",
      "state": "West Yorkshire",
      "zipCode": "LS1 5JD"
    },
    {
      "address": "20 Queen Square",
      "city": "Bristol",
      "state": "South West England",
      "zipCode": "BS1 4ND"
    },
    {
      "address": "15 Grey Street",
      "city": "Newcastle",
      "state": "Tyne and Wear",
      "zipCode": "NE1 6EE"
    },
    {
      "address": "1 Canary Wharf",
      "city": "London",
      "state": "Greater London",
      "zipCode": "E14 5AB"
    },
    {
      "address": "33 Queen Street",
      "city": "Cardiff",
      "state": "Wales",
      "zipCode": "CF10 2GQ"
    },
    {
      "address": "12 Castle Street",
      "city": "Liverpool",
      "state": "Merseyside",
      "zipCode": "L2 0NE"
    },
    {
      "address": "5 High Street",
      "city": "Oxford",
      "state": "Oxfordshire",
      "zipCode": "OX1 4AH"
    },
    {
      "address": "22 King Street",
      "city": "Cambridge",
      "state": "Cambridgeshire",
      "zipCode": "CB1 1LN"
    },
    {
      "address": "14 Royal Mile",
      "city": "Edinburgh",
      "state": "Scotland",
      "zipCode": "EH1 1RE"
    },
    {
      "address": "9 Albion Street",
      "city": "Leeds",
      "state": "West Yorkshire",
      "zipCode": "LS1 6AD"
    },
    {
      "address": "3 Corn Street",
      "city": "Bristol",
      "state": "South West England",
      "zipCode": "BS1 1HT"
    },
    {
      "address": "50 Bold Street",
      "city": "Liverpool",
      "state": "Merseyside",
      "zipCode": "L1 4EA"
    },
    {
      "address": "18 Grainger Street",
      "city": "Newcastle",
      "state": "Tyne and Wear",
      "zipCode": "NE1 5JE"
    },
    {
      "address": "7 Queen Street",
      "city": "Belfast",
      "state": "Northern Ireland",
      "zipCode": "BT1 6EA"
    },
    {
      "address": "25 Corporation Street",
      "city": "Birmingham",
      "state": "West Midlands",
      "zipCode": "B2 4RN"
    },
    {
      "address": "11 Market Street",
      "city": "Manchester",
      "state": "Greater Manchester",
      "zipCode": "M1 1WR"
    },
    {
      "address": "4 Bridge Street",
      "state": "Nottinghamshire",
      "city": "Nottingham",
      "zipCode": "NG1 2GA"
    },
    {
      "address": "16 Fargate",
      "city": "Sheffield",
      "state": "South Yorkshire",
      "zipCode": "S1 2HE"
    },
    {
      "address": "2 High Street",
      "city": "Exeter",
      "state": "Devon",
      "zipCode": "EX4 3LH"
    },
    {
      "address": "8 Castle Street",
      "city": "Southampton",
      "state": "Hampshire",
      "zipCode": "SO14 2DS"
    },
    {
      "address": "19 Queen Victoria Road",
      "city": "Coventry",
      "state": "West Midlands",
      "zipCode": "CV1 3RQ"
    },
    {
      "address": "6 Fishergate",
      "city": "Preston",
      "state": "Lancashire",
      "zipCode": "PR1 2NJ"
    },
    {
      "address": "13 High Street",
      "city": "Reading",
      "state": "Berkshire",
      "zipCode": "RG1 2AN"
    }
  ],
  "United States": [
    {
      "address": "350 5th Ave",
      "city": "New York",
      "state": "New York",
      "zipCode": "10118"
    },
    {
      "address": "405 Lexington Ave",
      "city": "New York",
      "state": "New York",
      "zipCode": "10174"
    },
    {
      "address": "1 Market St",
      "city": "San Francisco",
      "state": "California",
      "zipCode": "94105"
    },
    {
      "address": "1600 Amphitheatre Pkwy",
      "city": "Mountain View",
      "state": "California",
      "zipCode": "94043"
    },
    {
      "address": "1 Microsoft Way",
      "city": "Redmond",
      "state": "Washington",
      "zipCode": "98052"
    },
    {
      "address": "233 S Wacker Dr",
      "city": "Chicago",
      "state": "Illinois",
      "zipCode": "60606"
    },
    {
      "address": "600 Congress Ave",
      "city": "Austin",
      "state": "Texas",
      "zipCode": "78701"
    },
    {
      "address": "700 Exposition Park Dr",
      "city": "Los Angeles",
      "state": "California",
      "zipCode": "90037"
    },
    {
      "address": "401 Biscayne Blvd",
      "city": "Miami",
      "state": "Florida",
      "zipCode": "33132"
    },
    {
      "address": "151 3rd St",
      "city": "San Francisco",
      "state": "California",
      "zipCode": "94103"
    },
    {
      "address": "1 Beacon St",
      "city": "Boston",
      "state": "Massachusetts",
      "zipCode": "02108"
    },
    {
      "address": "1600 Pennsylvania Ave NW",
      "city": "Washington",
      "state": "District of Columbia",
      "zipCode": "20500"
    },
    {
      "address": "1201 Market St",
      "city": "Philadelphia",
      "state": "Pennsylvania",
      "zipCode": "19107"
    },
    {
      "address": "1001 Woodward Ave",
      "city": "Detroit",
      "state": "Michigan",
      "zipCode": "48226"
    },
    {
      "address": "200 E Randolph St",
      "city": "Chicago",
      "state": "Illinois",
      "zipCode": "60601"
    },
    {
      "address": "1 Peachtree Center Ave NE",
      "city": "Atlanta",
      "state": "Georgia",
      "zipCode": "30303"
    },
    {
      "address": "500 E Colorado Blvd",
      "city": "Pasadena",
      "state": "California",
      "zipCode": "91101"
    },
    {
      "address": "1401 Lawrence St",
      "city": "Denver",
      "state": "Colorado",
      "zipCode": "80204"
    },
    {
      "address": "201 E Washington St",
      "city": "Phoenix",
      "state": "Arizona",
      "zipCode": "85004"
    },
    {
      "address": "800 Nicollet Mall",
      "city": "Minneapolis",
      "state": "Minnesota",
      "zipCode": "55402"
    },
    {
      "address": "400 S Tryon St",
      "city": "Charlotte",
      "state": "North Carolina",
      "zipCode": "28202"
    },
    {
      "address": "600 Commerce St",
      "city": "Dallas",
      "state": "Texas",
      "zipCode": "75202"
    },
    {
      "address": "1 Canal St",
      "city": "New Orleans",
      "state": "Louisiana",
      "zipCode": "70130"
    },
    {
      "address": "1000 SW Broadway",
      "city": "Portland",
      "state": "Oregon",
      "zipCode": "97205"
    },
    {
      "address": "50 Public Square",
      "city": "Cleveland",
      "state": "Ohio",
      "zipCode": "44113"
    },
    {
      "address": "111 Monument Cir",
      "city": "Indianapolis",
      "state": "Indiana",
      "zipCode": "46204"
    },
    {
      "address": "400 W Capitol Ave",
      "city": "Little Rock",
      "state": "Arkansas",
      "zipCode": "72201"
    },
    {
      "address": "200 S Biscayne Blvd",
      "city": "Miami",
      "state": "Florida",
      "zipCode": "33131"
    },
    {
      "address": "1 E Washington St",
      "city": "Phoenix",
      "state": "Arizona",
      "zipCode": "85004"
    },
    {
      "address": "333 S Hope St",
      "city": "Los Angeles",
      "state": "California",
      "zipCode": "90071"
    }
  ]
};

const LOCAL_VERIFIED_ADDRESS_POOL_META = {
  "generatedAt": "2026-10-02T06:15:51.625Z",
  "countryCount": 19,
  "totalEntries": 570,
  "minEntriesPerCountry": 30,
  "maxEntriesPerCountry": 30,
  "minCitiesPerCountry": 5,
  "countryStats": {
    "Australia": {
      "entries": 30,
      "cities": 9
    },
    "Brazil": {
      "entries": 30,
      "cities": 8
    },
    "Canada": {
      "entries": 30,
      "cities": 12
    },
    "China": {
      "entries": 30,
      "cities": 20
    },
    "France": {
      "entries": 30,
      "cities": 9
    },
    "Germany": {
      "entries": 30,
      "cities": 9
    },
    "Hong Kong": {
      "entries": 30,
      "cities": 5
    },
    "India": {
      "entries": 30,
      "cities": 8
    },
    "Italy": {
      "entries": 30,
      "cities": 8
    },
    "Japan": {
      "entries": 30,
      "cities": 19
    },
    "Mexico": {
      "entries": 30,
      "cities": 6
    },
    "Netherlands": {
      "entries": 30,
      "cities": 8
    },
    "Russia": {
      "entries": 30,
      "cities": 8
    },
    "Singapore": {
      "entries": 30,
      "cities": 6
    },
    "South Korea": {
      "entries": 30,
      "cities": 19
    },
    "Spain": {
      "entries": 30,
      "cities": 8
    },
    "Taiwan": {
      "entries": 30,
      "cities": 6
    },
    "United Kingdom": {
      "entries": 30,
      "cities": 20
    },
    "United States": {
      "entries": 30,
      "cities": 24
    }
  }
};

if (typeof window !== 'undefined') {
  window.LOCAL_VERIFIED_ADDRESS_POOL = LOCAL_VERIFIED_ADDRESS_POOL_DATA;
  window.LOCAL_VERIFIED_ADDRESS_POOL_META = LOCAL_VERIFIED_ADDRESS_POOL_META;
}

if (typeof globalThis !== 'undefined') {
  globalThis.LOCAL_VERIFIED_ADDRESS_POOL = LOCAL_VERIFIED_ADDRESS_POOL_DATA;
  globalThis.LOCAL_VERIFIED_ADDRESS_POOL_META = LOCAL_VERIFIED_ADDRESS_POOL_META;
}
